AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for Web, Application, and DB tiers with Route 53 hosted zone."

Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            value: TestVPC
    
    InternetGateway:
      Type: AWS::EC2::InternetGateway

    VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

